// <auto-generated />
using System;
using EthereumBalanceNotifierBot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EthereumBalanceChecker.ConsoleApp.Migrations
{
    [DbContext(typeof(AddressesCheckerContext))]
    partial class AddressesCheckerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("EthereumBalanceNotifierBot.Database.Address", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Balance");

                    b.Property<bool>("BalanceChanged");

                    b.Property<decimal?>("BalanceGreaterThan");

                    b.Property<decimal?>("BalanceLowerThan");

                    b.Property<bool>("EveryTx");

                    b.Property<bool>("IsMessageSended");

                    b.Property<bool>("IsNotificationEnabled");

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("Name");

                    b.Property<long>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
